set escape '\';

-- CLEANUP

DELETE FROM "EAT"."M_FORM_FIELD" WHERE FORM_NAME = 'InstallGE';
DELETE FROM "EAT"."M_FORM_BUTTON" WHERE FORM_NAME = 'InstallGE';
DELETE FROM "EAT"."M_FORM" WHERE FORM_NAME = 'InstallGE';
DELETE FROM "EAT"."I_DICTIONARY" WHERE SIC LIKE 'field.inwi.installge.%';
DELETE FROM "EAT"."I_DICTIONARY" WHERE SIC LIKE 'btn.inwi.installge.%';


-- FORM
INSERT INTO "EAT"."M_FORM" (FORM_NAME, FORM_DESCRIPTION, MANAGER_CLASS, ENTITY_MANAGER, CLASS_NAME, PK_NAME, DOMAIN, FORM_LAYOUT) 
VALUES ('InstallGE', 'Install GE', 'srms.acquisition.forms.inwi.InstallGEFormService', 'GRANITE', 'model.inwi.InstallGE', 'nomSiteInstId', 'INWI', '2');


-- FORM FIELDS SICS
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'nomSiteInstId', 'Nominal Site Inst Id', 'nomSiteInstId', 'field.empty', 'N', 10, 0, 0, 0, 'Y', 51, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'nomSiteHumId', 'Nominal Site Humain Id', 'nomSiteHumId', 'field.empty', 'N', 0, 0, 0, 0, 'N', 52, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'siteInstId', 'Site Inst Id', 'siteInstId', 'field.empty', 'N', 10, 0, 0, 0, 'N', 53, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'ngoSrmsInstId', 'NGO Srms Inst Id', 'ngoSrmsInstId', 'field.empty', 'N', 10, 0, 0, 0, 'N', 54, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'responsableGE', 'Résponsable', 'responsableGE', 'field.inwi.installge.responsablege', 'Y', 0, 0, 0, 0, 'N', 55, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'responsableGEPhone', 'Téléphone du résponsable', 'responsableGEPhone', 'field.inwi.installge.responsablegephone', 'Y', 0, 0, 0, 0, 'N', 56, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'responsableGEEmail', 'Email du résponsable', 'responsableGEEmail', 'field.inwi.installge.responsablegeemail', 'Y', 0, 0, 0, 0, 'N', 57, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('InstallGE', 'typeGeLabel', 'Type', 'typeGe', 'field.inwi.installge.getype', 'Y', 0, 99, 8, 'Y', 10, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'typeGe', 'Type', 'typeGe', 'field.inwi.installge.getype', 'Y', 0, 0, 0, 0, 'N', 58, 'Y', 'Y', '*', '*', 'INWI', 150, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('InstallGE', 'ownershipGELabel', 'Ownership', 'ownershipGE', 'field.inwi.installge.geownership', 'Y', 0, 99, 9, 'Y', 310, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'ownershipGE', 'Ownership', 'ownershipGE', 'field.inwi.installge.geownership', 'Y', 0, 0, 0, 0, 'N', 59, 'Y', 'N', '*', '*', 'INWI', 450, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('InstallGE', 'snGELabel', 'Numéro de série', 'snGE', 'field.inwi.installge.gesn', 'Y', 0, 99, 10, 'Y', 610, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'snGE', 'Numéro de série', 'snGE', 'field.inwi.installge.gesn', 'Y', 0, 0, 0, 0, 'N', 60, 'Y', 'N', '*', '*', 'INWI', 750, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('InstallGE', 'installationDateGELabel', 'Date d installation', 'installationDateGE', 'field.inwi.installge.geinstallationdate', 'Y', 0, 99, 11, 'Y', 10, 40, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'installationDateGE', 'Date d installation', 'installationDateGE', 'field.inwi.installge.geinstallationdate', 'Y', 4, 4, 0, 0, 'N', 61, 'Y', 'N', '*', '*', 'INWI', 150, 50, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('InstallGE', 'commentGELabel', 'Commentaire', 'commentGE', 'field.inwi.installge.gecomment', 'N', 0, 99, 12, 'Y', 310, 40, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('InstallGE', 'commentGE', 'Commentaire', 'commentGE', 'field.inwi.installge.gecomment', 'N', 0, 10, 0, 0, 'N', 62, 'Y', 'N', '*', '*', 'INWI', 450, 50, 140, 20);


-- FORM FIELDS SICS
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.responsablege', 'FR', 'Résponsable', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.responsablegephone', 'FR', 'Téléphone du résponsable', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.responsablegeemail', 'FR', 'Email du résponsable', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.getype', 'FR', 'Type', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.geownership', 'FR', 'Ownership', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.gesn', 'FR', 'Numéro de série', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.geinstallationdate', 'FR', 'Date d installation', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.installge.gecomment', 'FR', 'Commentaire', 'INWI');


-- FORM BUTTONS
INSERT INTO "EAT"."M_FORM_BUTTON"(BUTTON_NAME, FORM_NAME, BUTTON_LABEL, ACTION, FORM_BIND, PRESENTATION_INDEX, BUTTON_SIC) 
VALUES ('InstallGE_confirm','InstallGE','Confirm','javascript:confirm()', 'N', 1, 'btn.inwi.installge.ok');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'btn.inwi.installge.ok', 'FR', 'Confirm', 'INWI');



COMMIT;
quit;
