set escape '\';

-- CLEANUP

DELETE FROM "EAT"."M_FORM_FIELD" WHERE FORM_NAME = 'UninstallGE';
DELETE FROM "EAT"."M_FORM_BUTTON" WHERE FORM_NAME = 'UninstallGE';
DELETE FROM "EAT"."M_FORM" WHERE FORM_NAME = 'UninstallGE';
DELETE FROM "EAT"."I_DICTIONARY" WHERE SIC LIKE 'field.inwi.uninstallge.%';
DELETE FROM "EAT"."I_DICTIONARY" WHERE SIC LIKE 'btn.inwi.uninstallge.%';


-- FORM

INSERT INTO "EAT"."M_FORM" (FORM_NAME, FORM_DESCRIPTION, MANAGER_CLASS, ENTITY_MANAGER, CLASS_NAME, PK_NAME, DOMAIN, FORM_LAYOUT) 
VALUES ('UninstallGE', 'Uninstall GE', 'srms.acquisition.forms.inwi.UninstallGEFormService', 'GRANITE', 'model.inwi.UninstallGE', 'nomSiteInstId', 'INWI', '2');


-- FORM FIELDS SICS

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'nomSiteInstId', 'Nominal Site Inst Id', 'nomSiteInstId', 'field.empty', 'N', 10, 0, 0, 0, 'Y', 51, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'nomSiteHumId', 'Nominal Site Humain Id', 'nomSiteHumId', 'field.empty', 'N', 0, 0, 0, 0, 'N', 52, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'siteInstId', 'Site Inst Id', 'siteInstId', 'field.empty', 'N', 10, 0, 0, 0, 'N', 53, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'ngoSrmsInstId', 'NGO Srms Inst Id', 'ngoSrmsInstId', 'field.empty', 'N', 10, 0, 0, 0, 'N', 54, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'responsableDesGE', 'Responsable Désinstallation GE', 'responsableDesGE', 'field.inwi.uninstallge.responsabledesge', 'Y', 0, 0, 0, 0, 'N', 55, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'responsableDesGEPhone', 'Responsable Désinstallation GE Phone', 'responsableDesGEPhone', 'field.inwi.uninstallge.responsabledesgephone', 'Y', 0, 0, 0, 0, 'N', 56, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'responsableDesGEEmail', 'Responsable Désinstallation GE Email', 'responsableDesGEEmail', 'field.inwi.uninstallge.responsabledesgeemail', 'Y', 0, 0, 0, 0, 'N', 57, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('UninstallGE', 'typeGeLabel', 'Type GE', 'typeGe', 'field.inwi.uninstallge.getype', 'Y', 0, 99, 8, 'Y', 10, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'typeGe', 'Type GE', 'typeGe', 'field.inwi.uninstallge.getype', 'Y', 0, 0, 0, 0, 'N', 58, 'Y', 'Y', '*', '*', 'INWI', 150, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('UninstallGE', 'ownershipGELabel', 'Location/propre', 'ownershipGE', 'field.inwi.uninstallge.geownership', 'Y', 0, 99, 9, 'Y', 310, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'ownershipGE', 'Location/propre', 'ownershipGE', 'field.inwi.uninstallge.geownership', 'Y', 0, 0, 0, 0, 'N', 59, 'Y', 'Y', '*', '*', 'INWI', 450, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('UninstallGE', 'snGELabel', 'Numéros de série', 'snGE', 'field.inwi.uninstallge.gesn', 'Y', 0, 99, 10, 'Y', 610, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'snGE', 'Numéros de série', 'snGE', 'field.inwi.uninstallge.gesn', 'Y', 0, 0, 0, 0, 'N', 60, 'Y', 'Y', '*', '*', 'INWI', 750, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('UninstallGE', 'desinstallationCommentGELabel', 'Commentaire désinstallation GE', 'desinstallationCommentGE', 'field.inwi.uninstallge.gedesinstallationcomment', 'Y', 0, 99, 11, 'Y', 10, 40, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'desinstallationCommentGE', 'Commentaire désinstallation GE', 'desinstallationCommentGE', 'field.inwi.uninstallge.gedesinstallationcomment', 'Y', 0, 10, 0, 0, 'N', 61, 'Y', 'N', '*', '*', 'INWI', 150, 50, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('UninstallGE', 'finInstallationDateGELabel', 'Date de désinstallation', 'finInstallationDateGE', 'field.inwi.uninstallge.m217fininstallationgeprov', 'N', 0, 99, 12, 'Y', 310, 40, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('UninstallGE', 'finInstallationDateGE', 'Date de désinstallation', 'finInstallationDateGE', 'field.inwi.uninstallge.m217fininstallationgeprov', 'N', 4, 4, 0, 0, 'N', 62, 'Y', 'N', '*', '*', 'INWI', 450, 50, 140, 20);


-- FORM FIELDS SICS

INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.responsabledesge', 'FR', 'Responsable Désinstallation GE', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.responsabledesgephone', 'FR', 'Responsable Désinstallation GE Phone', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.responsabledesgeemail', 'FR', 'Responsable Désinstallation GE Email', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.getype', 'FR', 'Type GE', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.geownership', 'FR', 'Location/propre', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.gesn', 'FR', 'Numéros de série', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.gedesinstallationcomment', 'FR', 'Commentaire désinstallation GE', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.uninstallge.m217fininstallationgeprov', 'FR', 'Date de désinstallation', 'INWI');


-- FORM BUTTONS

INSERT INTO "EAT"."M_FORM_BUTTON"(BUTTON_NAME, FORM_NAME, BUTTON_LABEL, ACTION, FORM_BIND, PRESENTATION_INDEX, BUTTON_SIC) 
VALUES ('UninstallGE_confirm','UninstallGE','Confirm','javascript:confirm()', 'N', 1, 'btn.inwi.uninstallge.ok');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'btn.inwi.uninstallge.ok', 'FR', 'Confirm', 'INWI');



COMMIT;
quit;