set escape '\';

-- CLEANUP

DELETE FROM "EAT"."M_FORM_FIELD" WHERE FORM_NAME = 'OnAir';
DELETE FROM "EAT"."M_FORM_BUTTON" WHERE FORM_NAME = 'OnAir';
DELETE FROM "EAT"."M_FORM" WHERE FORM_NAME = 'OnAir';
DELETE FROM "EAT"."I_DICTIONARY" WHERE SIC LIKE 'field.inwi.onair.%';
DELETE FROM "EAT"."I_DICTIONARY" WHERE SIC LIKE 'btn.inwi.onair.%';


-- FORM

INSERT INTO "EAT"."M_FORM" (FORM_NAME, FORM_DESCRIPTION, MANAGER_CLASS, ENTITY_MANAGER, CLASS_NAME, PK_NAME, DOMAIN, FORM_LAYOUT) 
VALUES ('OnAir', 'On Air', 'srms.onair.forms.inwi.OnAirFormService', 'GRANITE', 'model.inwi.OnAir', 'nomSiteInstId', 'INWI', '2');


-- FORM FIELDS SICS

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'nomSiteInstId', 'Nominal Site Inst Id', 'nomSiteInstId', 'field.empty', 'N', 10, 0, 0, 0, 'Y', 51, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'nomSiteHumId', 'Nominal Site Humain Id', 'nomSiteHumId', 'field.empty', 'N', 0, 0, 0, 0, 'N', 52, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'siteInstId', 'Site Inst Id', 'siteInstId', 'field.empty', 'N', 10, 0, 0, 0, 'N', 53, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'ngoSrmsInstId', 'NGO Srms Inst Id', 'ngoSrmsInstId', 'field.empty', 'N', 10, 0, 0, 0, 'N', 54, 'H', 'Y', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'onAirName', 'On Air Name', 'onAirName', 'field.inwi.onair.onairname', 'Y', 0, 0, 0, 0, 'N', 55, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'onAirPhone', 'On Air  Phone', 'onAirPhone', 'field.inwi.onair.onairphone', 'Y', 0, 0, 0, 0, 'N', 56, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'onAirEmail', 'On Air  Email', 'onAirEmail', 'field.inwi.onair.onairemail', 'Y', 0, 0, 0, 0, 'N', 57, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('OnAir', 'onAirDateLabel', 'Date On Air', 'onAirDate', 'field.inwi.onair.onairdate', 'Y', 0, 99, 8, 'Y', 10, 80, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'onAirDate', 'Date On Air', 'onAirDate', 'field.inwi.onair.onairdate', 'Y', 4, 4, 0, 0, 'N', 58, 'Y', 'N', '*', '*', 'INWI', 150, 90, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('OnAir', 'onAirBlockingLabel', 'Réserves blocantes', 'onAirBlocking', 'field.inwi.onair.onairblocking', 'Y', 0, 99, 9, 'Y', 310, 80, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'onAirBlocking', 'Réserves blocantes', 'onAirBlocking', 'field.inwi.onair.onairblocking', 'Y', 0, 2, 0, 0, 'N', 59, 'Y', 'N', '*', '*', 'INWI', 450, 90, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('OnAir', 'cleanUpRadioNameLabel', 'Clean up Radio', 'cleanUpRadioName', 'field.inwi.onair.cleanupradioname', 'N', 0, 99, 10, 'Y', 10, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'cleanUpRadioName', 'Clean up Radio', 'cleanUpRadioName', 'field.inwi.onair.cleanupradioname', 'N', 0, 0, 0, 0, 'N', 60, 'Y', 'Y', '*', '*', 'INWI', 150, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('OnAir', 'cleanUpRadioPhoneLabel', 'Clean up Radio Phone', 'cleanUpRadioPhone', 'field.inwi.onair.cleanupradiophone', 'N', 0, 99, 11, 'Y', 310, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'cleanUpRadioPhone', 'Clean up Radio Phone', 'cleanUpRadioPhone', 'field.inwi.onair.cleanupradiophone', 'N', 0, 0, 0, 0, 'N', 61, 'Y', 'Y', '*', '*', 'INWI', 450, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, PRESENTATION_INDEX, VISIBLE, POS_X, POS_Y, DOMAIN)
VALUES
('OnAir', 'cleanUpRadioEmailLabel', 'Clean up Radio Email', 'cleanUpRadioEmail', 'field.inwi.onair.cleanupradioemail', 'N', 0, 99, 12, 'Y', 610, 0, 'INWI');
INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'cleanUpRadioEmail', 'Clean up Radio Email', 'cleanUpRadioEmail', 'field.inwi.onair.cleanupradioemail', 'N', 0, 0, 0, 0, 'N', 62, 'Y', 'Y', '*', '*', 'INWI', 750, 10, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'm3_17CleanUpBlocanteMES', 'Clean up blocante MES', 'm3_17CleanUpBlocanteMES', 'field.inwi.onair.m317cleanupblocantemes', 'Y', 4, 4, 0, 0, 'N', 63, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);

INSERT INTO "EAT"."M_FORM_FIELD"
(FORM_NAME, FIELD_NAME, FIELD_DESCRIPTION, FIELD_CAPTION, FIELD_SIC, MANDATORY, FIELD_TYPE, FORM_FIELD_TYPE, MIN_LENGTH, MAX_LENGTH, PK, PRESENTATION_INDEX, VISIBLE, READ_ONLY, UPDATE_PRIVILEGE, VIEW_PRIVILEGE, DOMAIN, POS_X, POS_Y, WIDTH, HEIGHT)
VALUES
('OnAir', 'm3_11MiseEnAir', 'M3.11 Mise en air', 'm3_11MiseEnAir', 'field.inwi.onair.m311miseenair', 'Y', 4, 4, 0, 0, 'N', 64, 'H', 'N', '*', '*', 'INWI', 140, 0, 140, 20);


-- FORM FIELDS SICS

INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.onairname', 'FR', 'On Air Name', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.onairphone', 'FR', 'On Air  Phone', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.onairemail', 'FR', 'On Air  Email', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.onairdate', 'FR', 'Date On Air', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.onairblocking', 'FR', 'Réserves blocantes', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.cleanupradioname', 'FR', 'Clean up Radio', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.cleanupradiophone', 'FR', 'Clean up Radio Phone', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.cleanupradioemail', 'FR', 'Clean up Radio Email', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.m317cleanupblocantemes', 'FR', 'Clean up blocante MES', 'INWI');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'field.inwi.onair.m311miseenair', 'FR', 'M3.11 Mise en air', 'INWI');


-- FORM BUTTONS

INSERT INTO "EAT"."M_FORM_BUTTON"(BUTTON_NAME, FORM_NAME, BUTTON_LABEL, ACTION, FORM_BIND, PRESENTATION_INDEX, BUTTON_SIC) 
VALUES ('OnAir_confirm','OnAir','Confirm','javascript:confirm()', 'N', 1, 'btn.inwi.onair.ok');
INSERT INTO "EAT"."I_DICTIONARY" (ID, SIC, LANG_ID, MESSAGE, DOMAIN) VALUES (I_DICTIONARY_ID.NEXTVAL, 'btn.inwi.onair.ok', 'FR', 'Confirm', 'INWI');



COMMIT;
quit;